# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  docker:
      # specify the version you desire here
    - image: google/cloud-sdk
      # auth:
      #   username: _json_key
      #   password: $GCLOUD_SERVICE_KEY

  working_directory: ~/repo

install_npm_packages: &install_npm_packages
  run:
    name: Install Npm Dependencies
    command: yarn install

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/travela-backend

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      # - *attach_workspace
      - run:
          name: Authenticate to gcloud
          command: |
            chmod +x scripts/gcloud_login.sh
            scripts/gcloud_login.sh main
      - run:
          name: Install and setup K8s deployment requirements
          command: |
            chmod +x ./run.sh
            ./run.sh

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build