kind: Service
apiVersion: v1
metadata:
  name: app-deployment
spec:
  selector:
    app: app-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app-deployment
        image: gcr.io/${PROJECT_ID}/app-deployment:${CIRCLE_SHA1}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
